### ISSUE TITLE
Support room versioning

### ISSUE THREAD

**Issue by bwindels** [element-hq/hydrogen-web#227]
multiple rooms need to merged into one, with their timeline stitched together:
 - [ ] in timelineFragment, the nextId and previousId fields should contain the full key including the room id rather than just the fragment id. This way their pointers can point across rooms.
 - [ ] the roomSummary store gains a `previousRoomVersions` field, containing an array with the room ids 
 - [ ] when receiving a tombstone event:
   - [ ] update the room summary: change the room id of the room summary to the new, superseding room id while adding the current room id to the previousRoomVersions field.
   - [ ] create a new timeline fragment for the new room and point the old timeline fragment to it
- [ ] how do we handle updates to replaced rooms? by default it wouldn't find the room anymore and hence create a new one. We want to store the update except for the room summary, which should only be changed by the last room.

**Comment by MidhunSureshR** [comment]
Another possibility:
- We can make the RoomSummary also a doubly linked list in storage and we only render the the room in the left panel if it is not connected to another (next) RoomSummary. This will allow us to lookup the most recent version of the room which is useful for permalink.
- Show no room change in the UI by having fragment entries that link across rooms i.e timeline appears continuous.
  Will require adding room-id to fragment entries.
- Render a tile for the tombstone event which indicates that the room version changed.
- Navigation should also use the doubly linked RoomSummary to translate a given room-id to the most latest room-id.
- If you get a new room via sync with a previous version:
    - If you were not a member of the previous room, you cannot scroll to the messages before the upgrade.
    - If you were a member, you know of the old room and should link the room summaries.

**Comment by bwindels** [comment]
To be able to look up a `RoomSummary` by the room id of a previous version of the room, the `RoomSummary` store could have a [`multiEntry`](https://developer.mozilla.org/docs/Web/API/IDBIndex/multiEntry) index on the `previousRoomVersions` field.
