### ISSUE TITLE
End-to-end encryption

### ISSUE THREAD

**Issue by bwindels** [element-hq/hydrogen-web#29]
## TODO
 - [x] have a basic idea of how we would build a wasm/asm.js version of the sdk. See https://github.com/vector-im/crypto-wrapper-hydrogen/, but deciding not to go this way, mainly because it's a PITA to debug and because we will need more flexibility to make E2EE fast enough in IE11 than the sdk can offer (run olm decryption in a web worker, ...), and asm.js seems very slow in IE11 so the fewer asm.js (e.g. libolm) we can run, the better.
 - [x] persist olm account in session store
 - [x] upload identity keys and OTKs after login
 - [x] sync `device_one_time_keys_count` and upload more OTKs if needed
 - [x] device tracking in e2ee rooms
 - [x] decrypt olm messages, persisting olm sessions
 - [x] handle to_device messages and decrypt them
 - [x] store room keys shared over olm as inbound megolm sessions
 - [x] decrypt megolm encrypted messages
 - [ ] don't remove `olmAccount` and `areDeviceKeysUploaded ` keys from session store when clearing the session, otherwise e2ee keys would rotate while keeping same device id/access token. Important to do this before doing a release!
 - [x] encrypt olm messages over to_device
 - [x] start new megolm outbound sessions, store them and share them over olm with required devices
 - [x] send megolm encrypted messages
 - [x] mark events as verified
 - [x] rotate megolm session when member changes , and share our outbound session at the current ratchet position with new members?
 - [x] make it fast on IE11
 - [x] make sure decryption errors don't block other events from being decryption, or block the client.
 - [ ] block multiple open sessions
 - [ ] write unit tests

## Remaining questions/remarks wrt to rust-sdk (not relevant anymore atm)
  - how to implement CryptoStore? Try to anticipate all the data that will be requested and preload a memory store? Or actually implement something that calls into idb? If this breaks, it would be painful to debug. E.g. before we call `receive_sync_response`, go over all `to_device` messages encrypted with olm and get their `sender_key`.
  - One way or another, I don't think it will be very feasible to have the `OlmMachine` live longer than one of our txns.
 - sync responses will be parsed and loaded into memory twice :(

**Comment by bwindels** [comment]
cleanup libolm d.ts definitions as well

**Comment by bwindels** [comment]
do more input validation as well

**Comment by bwindels** [comment]
also explicitly don't support having it open in multiple tabs
